### ISSUE TITLE
Training crash

### ISSUE THREAD

**Issue by haihaoshen** [richzhang/colorization#16]
Hi,

I used my own data to train the net, but got the below error message. Could you please show some hints? Thanks.

I1203 01:20:34.406128 11072 net.cpp:165] Memory required for data: 7864320
I1203 01:20:34.406141 11072 layer_factory.hpp:77] Creating layer nongray_mask
Traceback (most recent call last):
  File "/tmp/colorization/resources/caffe_traininglayers.py", line 4, in <module>
    import numpy as np
  File "/usr/local/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/__init__.py", line 58, in <module>
    from numpy.testing.nosetester import _numpy_tester
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/__init__.py", line 12, in <module>
    from . import decorators as dec
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/decorators.py", line 21, in <module>
    from .utils import SkipTest
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 15, in <module>
    from tempfile import mkdtemp, mkstemp
  File "/usr/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/tmp/colorization/caffe-colorization/python/caffe/io.py", line 2, in <module>
    import skimage.io
  File "/usr/lib/python2.7/dist-packages/skimage/__init__.py", line 166, in <module>
    from .util.dtype import *
  File "/usr/lib/python2.7/dist-packages/skimage/util/__init__.py", line 1, in <module>
    from .dtype import (img_as_float, img_as_int, img_as_uint, img_as_ubyte,
  File "/usr/lib/python2.7/dist-packages/skimage/util/dtype.py", line 8, in <module>
    dtype_range = {np.bool_: (False, True),
AttributeError: 'module' object has no attribute 'bool_'

**Comment by haihaoshen** [comment]
after set correct PYTHONPATH, the issue solved.
